### ISSUE TITLE
spyse.response.RateLimitError: too many requests

### ISSUE THREAD

**Issue by ghost** [spyse-com/cli#3]
Hi,

I have this error when I try to scan a domain or subdomains.
`echo tesla.com | spysecli --api_token=$SPYSE_API subdomains`
```
Traceback (most recent call last):
  File "/usr/local/bin/spysecli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/bin/main.py", line 46, in cli
    client.fetch_account(f)
  File "/usr/local/lib/python3.9/site-packages/spysecli/client.py", line 23, in fetch_account
    callback_f(self.client.get_quotas())
  File "/usr/local/lib/python3.9/site-packages/spyse/client.py", line 106, in get_quotas
    response.check_errors()
  File "/usr/local/lib/python3.9/site-packages/spyse/response.py", line 117, in check_errors
    raise RateLimitError(m)
spyse.response.RateLimitError: too many requests
```
Any ideas ?

**Comment by fabelx** [comment]
Same issue.

**Comment by Retro64XYZ** [comment]
I have the same problem.
